

INSERT INTO users (username, password, email) VALUES ('testikayttaja1', 'salasana123', 'testi1@gmail.com') ON CONFLICT DO NOTHING;
INSERT INTO users (username, password, email) VALUES ('testikayttaja2', 'salasana123', 'testi2@gmail.com') ON CONFLICT DO NOTHING;
INSERT INTO users (username, password, email) VALUES ('testikayttaja3', 'salasana123', 'testi3@gmail.com') ON CONFLICT DO NOTHING;
INSERT INTO users (username, password, email) VALUES ('testikayttaja4', 'salasana123', 'testi4@gmail.com') ON CONFLICT DO NOTHING;
INSERT INTO users (username, password, email) VALUES ('testikayttaja5', 'salasana123', 'testi5@gmail.com') ON CONFLICT DO NOTHING;

INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, complies_with_regulations) VALUES (1, 'sell', 'Digestion', 'pickup', 'one time', 1, 'tn', 250, 'Biokaasulaitoksen mädätettä. Kuivamädäte.', 'Papinkankaantie 15, 80330 Joensuu', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, complies_with_regulations) VALUES (1, 'sell', 'Wood',  'pickup', 'one time', 1, 'tn', 700, 'Kuiaa jalavaa, vaahteraa ja harvennuspuuta metsätien varrelta.', 'Tampereentie 5, 31670 Urjala', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, complies_with_regulations) VALUES (2, 'sell', 'Plant-based biomasses',  'pickup', 'one time', 1, 'tn', 300, 'Harvennuspuuta Suomesta.', 'Vattuperkkiöntie 2, 85500 Nivala', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, complies_with_regulations) VALUES (2, 'sell', 'Grass, waste fodder and green growths',  'pickup', 'one time', 1, 'tn', 30, 'Vanhempia luomukelpoisia säilörehunurmia noin 10 ha.', 'Siggansintie 3, 10140 Siuntio', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, complies_with_regulations) VALUES (3, 'sell', 'Grass, waste fodder and green growths',  'pickup', 'one time', 1, 'tn', 40, 'Vanhempia luomukelpoisia säilörehunurmia noin 10 ha.', 'Åtorpintie 60, 07280 Porvoo', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, complies_with_regulations) VALUES (3, 'sell', 'Grass, waste fodder and green growths',  'pickup', 'one time', 1, 'tn', 75, 'Ylimääräistä viherkasvustoa halvalla.', 'Porokartanontie 1, Sodankylä', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, complies_with_regulations) VALUES (4, 'sell', 'Wood',  'pickup', 'one time', 1, 'tn', 550, 'Kuivaa jalavaa, vaahteraa ja harvennuspuuta metsätien varrella.', 'Isokoskentie, Kiiskilä', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, complies_with_regulations) VALUES (4, 'sell', 'Wood',  'pickup', 'one time', 1, 'tn', 710, 'Rikkinäisiä kuorma-lavoja.', 'Rantakankaantie 16, Alajärvi', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, complies_with_regulations) VALUES (4, 'sell', 'Basket fodder',  'pickup', 'one time', 1, 'tn', 35, 'Vuoden 2022 säilörehupaaleja, verkot ja muovit osin rikki.', 'Männiköntie 10, 41400 Jyväskylä', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, complies_with_regulations) VALUES (5, 'sell', 'Soil and growing media',  'pickup', 'one time', 1, 'tn', 1000, 'Ylimääräistä maa-ainesta halvalla.', 'Uudenkyläntie 182, 58700 Sulkava', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, complies_with_regulations) VALUES (5, 'sell', 'Other side streams (not biomass)',  'pickup', 'one time', 1, 'tn', 40, 'Fossiilittomasti tuotetun tuhkan neutralointikyky on 26-30 % Ca. Raskasmetallipitoisuudet alittavat lannoiteasetuksen peltolevityksen raja-arvot.', 'Ritolantie 30, 60720 Ilmajoki', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, complies_with_regulations) VALUES (5, 'sell', 'Animal-based biomasses',  'pickup', 'one time', 1, 'tn', 15, 'Mädätteitä Suomesta.', 'Hakalantie 3, 86710 Kärsämäki', '1') ON CONFLICT DO NOTHING;


 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, coordinates, complies_with_regulations) VALUES (4, 'sell', 'Basket fodder',  'pickup', 'one time', 1, 'tn', 35, 'Vuoden 2022 säilörehupaaleja, verkot ja muovit osin rikki.', 'Männiköntie 10, 41400 Jyväskylä', '(26.214065536083947, 62.264343999999994)', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, coordinates,complies_with_regulations) VALUES (2, 'sell', 'Plant-based biomasses',  'pickup', 'one time', 1, 'tn', 300, 'Harvennuspuuta Suomesta.', 'Vattuperkkiöntie 2, 85500 Nivala', '(24.9342153, 63.8923984)', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, coordinates,complies_with_regulations) VALUES (5, 'sell', 'Other side streams (not biomass)',  'pickup', 'one time', 1, 'tn', 40, 'Fossiilittomasti tuotetun tuhkan neutralointikyky on 26-30 % Ca. Raskasmetallipitoisuudet alittavat lannoiteasetuksen peltolevityksen raja-arvot.', 'Ritolantie 30, 60720 Ilmajoki', '(22.7118248, 62.7315596)', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, coordinates,complies_with_regulations) VALUES (5, 'sell', 'Soil and growing media',  'pickup', 'one time', 1, 'tn', 1000, 'Ylimääräistä maa-ainesta halvalla.', 'Uudenkyläntie 182, 58700 Sulkava', '(28.323367600537907, 61.79652605)', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, coordinates,complies_with_regulations) VALUES (1, 'sell', 'Digestion',  'pickup', 'one time', 1, 'tn', 250, 'Biokaasulaitoksen mädätettä. Kuivamädäte.', 'Papinkankaantie 15, 80330 Joensuu', '(29.8356994, 62.5668921)', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, coordinates,complies_with_regulations) VALUES (5, 'sell', 'Animal-based biomasses',  'pickup', 'one time', 1, 'tn', 15, 'Mädätteitä Suomesta.', 'Hakalantie 3, 86710 Kärsämäki', '(25.7667884, 63.9603873)', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, coordinates,complies_with_regulations) VALUES (3, 'sell', 'Grass, waste fodder and green growths',  'pickup', 'one time', 1, 'tn', 75, 'Ylimääräistä viherkasvustoa halvalla.', 'Porokartanontie 1, Sodankylä', '(27.3667281, 68.3336791)', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, coordinates,complies_with_regulations) VALUES (2, 'sell', 'Grass, waste fodder and green growths',  'pickup', 'one time', 1, 'tn', 30, 'Vanhempia luomukelpoisia säilörehunurmia noin 10 ha.', 'Siggansintie 3, 10140 Siuntio', '(24.1444409, 60.1367265)', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, coordinates,complies_with_regulations) VALUES (3, 'sell', 'Grass, waste fodder and green growths',  'pickup', 'one time', 1, 'tn', 40, 'Vanhempia luomukelpoisia säilörehunurmia noin 10 ha.', 'Åtorpintie 60, 07280 Porvoo', '(25.7364406, 60.4667942)', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, coordinates,complies_with_regulations) VALUES (4, 'sell', 'Wood',  'pickup', 'one time', 1, 'tn', 550, 'Kuivaa jalavaa, vaahteraa ja harvennuspuuta metsätien varrella.', 'Isokoskentie, Kiiskilä', '(24.6858813, 63.8003589)', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, coordinates,complies_with_regulations) VALUES (1, 'sell', 'Wood',  'pickup', 'one time', 1, 'tn', 700, 'Kuivaa jalavaa, vaahteraa ja harvennuspuuta metsätien varrelta.', 'Tampereentie 5, 31670 Urjala', '(23.5494974, 61.0815604)', '1') ON CONFLICT DO NOTHING;
 INSERT INTO listings (user_id, listing_type, category, delivery_method, supply_demand, batch_size, batch_units, price, description, address, coordinates,complies_with_regulations) VALUES (4, 'sell', 'Wood',  'pickup', 'one time', 1, 'tn', 710, 'Rikkinäisiä kuorma-lavoja.', 'Rantakankaantie 16, Alajärvi', '(23.9481132, 62.8319709)', '1') ON CONFLICT DO NOTHING;