services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - postgres
    stop_grace_period: 100ms

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
      - ./db_mock_data.sql:/db_mock_data.sql
    container_name: mtk-postgres