name: Deploy to staging

on:
  push:
    branches:
      - main
    tags:
      - v0.*

jobs:
    test:
        uses: ./.github/workflows/test.yml

    build-and-push:
        runs-on: ubuntu-latest
        needs: test
      
        steps:
          - uses: actions/checkout@v3
      
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}

          - name: Extract metadata
            id: meta
            uses: docker/metadata-action@v4
            with:
              images: mtkohtu/mtk-ohtu
              tags: |
                type=raw,value=latest,enable={{is_default_branch}}

          - name: Build and push
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}


