name: Tests

on: [workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: testpass
          POSTGRES_USER: testuser
          POSTGRES_DB: testbase

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Poetry
        run: pip install poetry
        
      - name: Install dependencies
        run: poetry install

      #- name: Prepare test data and start the application
      #  run: docker compose -f compose.ci.yml up -d
        
      - name: Run tests
        run: poetry run coverage run --branch -m pytest
        env:
          DATABASE_URL: localhost
          DATABASE_NAME: testbase
          DATABASE_USER: testuser
          DATABASE_PASSWORD: testpass
          DATABASE_PORT: 5432
          NOMINATIM_DOMAIN: nominatim.openstreetmap.org
          NOMINATIM_USER_AGENT: mtk-ohtu-app

      - name: Coverage report
        run: poetry run coverage xml
        
      - name: Pylint
        run: poetry run pylint src

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
